### ISSUE TITLE
Conformance: Error code for Blob/Manifest Unsupported

### ISSUE THREAD

**Issue by amouat** [opencontainers/distribution-spec#136]
The tests check for a 400 when deleting a blob/manifest is unsupported, but I think it should be a 405 according to the spec:

https://github.com/opencontainers/distribution-spec/blob/master/conformance/04_management_test.go#L68-L84

https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-method-not-allowed
https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-not-allowed-1

**Comment by pmengelbert** [comment]
@amouat The issue in that test is manifest deletion _by tag_.  According to the spec as currently written: "Note that a manifest can only be deleted by digest".
https://github.com/opencontainers/distribution-spec/blob/master/spec.md#delete-manifest

That said, 405 does make more sense, but there is nothing in the spec regarding what error code this situation should return. Probably better to just check that the error is in the 400 range, rather than commit to 400 or 405 specifically, since it's not specified

**Comment by amouat** [comment]
Yeah, but the test already doesn't agree with the spec. The test explicitly _allows_ for delete by tag to succeed and in the case of failure checks for 400 and the `UNSUPPORTED` code. If the UNSUPPORTED code is expected, I definitely think it should be a 405.

I think this was discussed on an issue before. Several registries apparently allow delete by tag IIRC, so the tests needed to allow for that (I guess the spec should also be updated but that hasn't happened yet).

**Comment by pmengelbert** [comment]
@amouat I think adding the 405 here is worthwhile. I'm preparing a pr with small changes, and I'll include this too.
