### ISSUE TITLE
Why do resumable uploads require a unique ID if digests are unique themselves?

### ISSUE THREAD

**Issue by atlaskerr** [opencontainers/distribution-spec#31]
So it's my understanding that when doing resumable uploads, the server presents you with a unique ID and a location header pointing to the resource being uploaded. Since the digest is unique, is the upload ID necessary?

**Comment by manishtomar** [comment]
Yes because the digest cannot be trusted until the full payload is received and verified against the digest.

**Comment by jonjohnsonjr** [comment]
Also, many clients compute digests lazily (gzip can be slow), so they won't even know the digest until they've finished the upload.

**Comment by atlaskerr** [comment]
@manishtomar But the unique id has to do with pointing the client to a location to resume the upload right? Couldn't that be done with just the digest? If payload is invalid then the uploads endpoint defines a `DIGEST_INVALID` that can be thrown.

@jonjohnsonjr Shouldn't the client know beforehand what the digest of a blob is before the upload even takes place?

**Comment by jonjohnsonjr** [comment]
@atlaskerr often not. The docker CLI gzips blobs the first time it writes them to the registry, see [here](https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/distribution/push_v2.go#L462-L474).

**Comment by atlaskerr** [comment]
What would you say to stating in the spec that clients MUST know the digest of a blob before they upload to the registry? @mikebrow I know you were wanting to formalize the absolute requirements of the specification.

**Comment by jonjohnsonjr** [comment]
I would strongly oppose that because it would be breaking for nearly every client and several registry implementations.

**Comment by atlaskerr** [comment]
I'm a little confused on what is open for change and what isn't. Is everything already set in stone?

@vbatts the server would still do a checksum at the end when it has received all of the blob's bytes.

**Comment by dmcgowan** [comment]
@atlaskerr please review the approved proposal for the distribution spec https://github.com/opencontainers/tob/blob/master/proposals/distribution.md

We will not accept changes which make existing registries which already implement the distribution specification as non-compliant or requiring changes. The v1.0 of this specification is designed to standardize the distribution protocol which is currently in use, not to create a better (but unused) protocol. We have defined a scope table that will allow for future improvements. These future improvements will take an implementation and adoption first approach rather than standards first. Please don't take the rejection of such changes as the maintainers believing we know best, but rather as a way to protect the standard and ensure that as many registries are 1.0 compliant.

**Comment by atlaskerr** [comment]
@dmcgowan I totally understand. Thanks for the clarification. I'm new to the project and was just looking for guidance. I'll bring my ideas back up after v1.0

**Comment by vbatts** [comment]
@atlaskerr and i'm glad for your questions and review!

**Comment by dmcgowan** [comment]
> I'll bring my ideas back up after v1.0

Feel free to discuss them now. For 1.0 we just want to ensure that any changes can be made in a way that registries which do not adopt those changes can still work with clients. In those cases, we might just ask for more proof that the change could work with existing clients which already use the protocol. For 1.1+, I think we are OK saying that all registries are 1.0, but only some may not be 1.1. That could make some of the discussions about a header defining the version as a necessary 1.0 change (i.e. registries may define the header, but if they don't the client must assume 1.0, but never 1.1+).

I want to echo what Vincent said and please don't be discouraged, we do appreciate the discussion and interest in improving the specification even if we don't always have time to respond quickly.
