### ISSUE TITLE
Create manifests as pointers to blobs instead of posting JSON.

### ISSUE THREAD

**Issue by atlaskerr** [opencontainers/distribution-spec#33]
The current spec states that clients can create image manifests by posting JSON after all blobs have been uploaded to the registry server. Since manifests are uploaded to the registry as blobs, It seems like it would be cleaner to have clients simply specify which blobs should be recognized as manifests instead of re-uploading content that the registry already has.

**Comment by jonjohnsonjr** [comment]
> Since manifests are uploaded to the registry as blobs

I don't think clients usually upload manifests as blobs (i.e. via the `/blobs/` endpoint). For images, they upload the layers + config, then PUT the manifest via the `/manifests/` endpoint.

> have clients simply specify which blobs should be recognized as manifests

We could possibly do this via media types. The blobs vs manifests distinction is kind of annoying/limiting, but useful for maintaining dependency graphs for garbage collection.

This is tangentially related to something @stevvooe mentioned recently re: [type-based rather than path-based model](https://groups.google.com/a/opencontainers.org/d/msg/dev/U49AZRFo3tk/A5kKdi3aBgAJ) for distribution, he might have some thoughts.

**Comment by atlaskerr** [comment]
@jonjohnsonjr Thanks for the rundown and link. I found out a few days ago that the docker registry didn't allow for fetching manifests from the blob endpoint and it threw me for a loop. It seems like implementation details are leaking into the spec, I would love to make this a priority for discussion after the `V1` release.

@stevvooe I agree with using a type-based instead of a path-based model for distribution. Registry implementations seem to be doing a lot of heavy lifting for the clients in exchange for losing true content-addressability. Would love to hear your thoughts on the subject.
