### ISSUE TITLE
Descriptions contain docker schema 1 concepts

### ISSUE THREAD

**Issue by jonjohnsonjr** [opencontainers/distribution-spec#60]
A few things leftover from schema 

## TAG_INVALID

The `TAG_INVALID` description says:
> During a manifest upload, if the tag in the manifest does not match the uri tag, this error will be returned.

Manifests no longer contains tags, so we should update this. A couple options:
1. Remove the error entirely.
2. Use this error if the client tries to use a tag that doesn't match the expected format. Ref https://github.com/opencontainers/distribution-spec/issues/52

## Signatures

There are 8 uses of the word `signature` in the spec. AFAIK, manifest signatures aren't really a thing after docker v2 schema 1.

For example, the `MANIFEST_UNVERIFIED` description says:
> During manifest upload, if the manifest fails signature verification, this error will be returned.

I assume we'd want to just remove that.

The rest of the instances of "signatures" refer to JWS payloads and such that don't make sense anymore, so we want to drop those descriptions and make sure the surrounding paragraphs still make sense.

**Comment by jonjohnsonjr** [comment]
cc @atlaskerr

**Comment by hallyn** [comment]
Related to this, the 'Pulling An Image" section's json spec for a manifest still lists the schema1 format for a manifest (i.e. https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md , specifying fsLayers instead of https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md Layers []) .  Is that intended?  Should a repo and/or client use the opencontainers/image-spec (https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/manifest.go) or not?  If so I can do an update to distribution-spec to update the json example.

**Comment by jdolitsky** [comment]
Resolved by #206
